---
- name: Install Requirements on EC2 instances
  hosts: ec2_instances
  become: yes
  tasks:
    - name: Copy installation script to remote hosts
      copy:
        src: /home/mujimmy/Desktop/UltimateDevOps_Project/Scripts/k8s.sh  # Replace with your script path
        dest: /tmp/script.sh
        mode: '0755'

    - name: Execute installation script
      shell: /tmp/script.sh
      register: script_output

    - name: Display script output
      debug:
        var: script_output.stdout_lines

    - name: Clean up script
      file:
        path: /tmp/script.sh
        state: absent