---
- name: Test EC2 Connectivity
  hosts: ec2_instances
  become: yes
  tasks:
    - name: Ping test
      ping:

    - name: Check system uptime
      command: uptime
      register: system_uptime

    - name: Display uptime
      debug:
        var: system_uptime.stdout